# Port Metadata
PORTNAME =          sh4zam
PORTVERSION =       1.0.0

MAINTAINER =        Falco Girgis <gyrovorbis@gmail.com>
LICENSE =           MIT
SHORT_DESC =        Hardware accelerated math and linear algebra library for the SH4.
ARCHS_SUPPORTED =   dreamcast

PORT_BUILD =        cmake

GIT_REPOSITORY =    https://github.com/gyrovorbis/sh4zam.git

TARGET =            libsh4zam.a
HDR_DIRECTORY = 	include/sh4zam
HDR_INSTDIR =       sh4zam
EXAMPLES_DIR =      example

include ${KOS_PORTS}/scripts/kos-ports.mk
