# Port Metadata
PORTNAME = 			libfast
PORTVERSION = 		0.0.1

MAINTAINER =        Nobody
LICENSE =           LGPL 2.1
SHORT_DESC =        Very optimized set of functions for the Sega Dreamcast

DEPENDENCIES =      

# What files we need to download, and where from.
GIT_REPOSITORY =    https://github.com/sega-dreamcast/libfast.git

TARGET =			libfast.a
INSTALLED_HDRS =	include/fast.h
HDR_INSTDIR =       fast

# KOS Distributed extras (to be copied into the build tree)
KOS_DISTFILES =		KOSMakefile.mk

include ${KOS_PORTS}/scripts/kos-ports.mk
