# Port Metadata
PORTNAME =          SDL
PORTVERSION =       1.2.15

MAINTAINER =        Nobody
LICENSE =           LGPLv2.1
SHORT_DESC =        Simple Directmedia Library

# No dependencies beyond the base system.
DEPENDENCIES =

# What files we need to download, and where from.
GIT_REPOSITORY =    https://github.com/libsdl-org/SDL-1.2.git

KOS_MAKEFILE =      Makefile.dc

TARGET =            libSDL.a
HDR_DIRECTORY =     include
HDR_INSTDIR =       SDL

include ${KOS_PORTS}/scripts/kos-ports.mk
